### ISSUE TITLE
When linking with jasper-3.0.3 tests fail due to segfaults

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-grib_util#151]
```
ed@mikado:~/NCEPLIBS-grib_util/b/tests$ bash -x ./run_cnvgrib_tests.sh 
+ set -e
+ echo ''

+ echo '*** Running cnvgrib test'
*** Running cnvgrib test
+ ../src/cnvgrib/cnvgrib -g21 ref_gdaswave.t00z.wcoast.0p16.f000.grib2 test_gdaswave.t00z.wcoast.0p16.f000.grib1
cnvgrib: /home/ed/Downloads/jasper-3.0.3/src/libjasper/base/jas_init.c:919: jas_get_ctx_internal: Assertion `ctx' failed.

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7f35a5319700 in ???
#1  0x7f35a53188a5 in ???
#2  0x7f35a4fdd08f in ???
	at /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
#3  0x7f35a4fdd00b in __GI_raise
	at ../sysdeps/unix/sysv/linux/raise.c:51
#4  0x7f35a4fbc858 in __GI_abort
	at /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:79
#5  0x7f35a4fbc728 in __assert_fail_base
	at /build/glibc-SzIz7B/glibc-2.31/assert/assert.c:92
#6  0x7f35a4fcdfd5 in __GI___assert_fail
	at /build/glibc-SzIz7B/glibc-2.31/assert/assert.c:101
#7  0x7f35a5691996 in ???
#8  0x7f35a56944ee in ???
#9  0x7f35a5694512 in ???
#10  0x7f35a56945f2 in ???
#11  0x561c69059e1e in dec_jpeg2000_
	at /home/ed/Downloads/NCEPLIBS-g2-3.4.5/src/dec_jpeg2000.c:69
#12  0x561c6904e6f0 in jpcunpack_
	at /home/ed/Downloads/NCEPLIBS-g2-3.4.5/src/jpcunpack.f:43
#13  0x561c6904c6b4 in gf_unpack7_
	at /home/ed/Downloads/NCEPLIBS-g2-3.4.5/src/gf_unpack7.f:95
#14  0x561c69046e11 in getgb2r_
	at /home/ed/Downloads/NCEPLIBS-g2-3.4.5/src/getgb2r.f:272
#15  0x561c69046409 in getgb2_
	at /home/ed/Downloads/NCEPLIBS-g2-3.4.5/src/getgb2.f:271
#16  0x561c6903ac72 in cnv21_
	at /home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnv21.F90:50
#17  0x561c6903c495 in cnvgrib
	at /home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnvgrib.F90:242
#18  0x561c690354be in main
	at /home/ed/NCEPLIBS-grib_util/src/cnvgrib/cnvgrib.F90:256
./run_cnvgrib_tests.sh: line 11: 11019 Aborted                 (core dumped) ../src/cnvgrib/cnvgrib -g21 ref_gdaswave.t00z.wcoast.0p16.f000.grib2 test_gdaswave.t00z.wcoast.0p16.f000.grib1

```

**Comment by edwardhartnett** [comment]
This was fixed in the g2 library.
