### ISSUE TITLE
memory leak in wgrib

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-grib_util#98]
Well the very first time I used wgrib, I found a memory leak. ;-)

```
+ ../src/wgrib/wgrib gdaswave.t00z.wcoast.0p16.f000.grib1
1918
1:0:d=21113000:WIND:kpds5=32:kpds6=1:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:sfc:anl:NAve=0
1919
2:19822:d=21113000:WDIR:kpds5=31:kpds6=1:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:sfc:anl:NAve=0
1920
3:46544:d=21113000:UGRD:kpds5=33:kpds6=1:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:sfc:anl:NAve=0
1921
4:66366:d=21113000:VGRD:kpds5=34:kpds6=1:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:sfc:anl:NAve=0
1922
5:87568:d=21113000:HTSGW:kpds5=100:kpds6=1:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:sfc:anl:NAve=0
1923
6:104630:d=21113000:PERPW:kpds5=108:kpds6=1:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:sfc:anl:NAve=0
1924
7:123072:d=21113000:DIRPW:kpds5=107:kpds6=1:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:sfc:anl:NAve=0
1925
8:147034:d=21113000:WVHGT:kpds5=102:kpds6=1:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:sfc:anl:NAve=0
1926
9:157432:d=21113000:SWELL:kpds5=105:kpds6=241:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:ordered sequence of data:anl:NAve=0
1927
10:174494:d=21113000:SWELL:kpds5=105:kpds6=241:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:ordered sequence of data:anl:NAve=0
1928
11:190088:d=21113000:SWELL:kpds5=105:kpds6=241:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:ordered sequence of data:anl:NAve=0
1929
12:203782:d=21113000:WVPER:kpds5=103:kpds6=1:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:sfc:anl:NAve=0
1930
13:215460:d=21113000:SWPER:kpds5=106:kpds6=241:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:ordered sequence of data:anl:NAve=0
1931
14:235282:d=21113000:SWPER:kpds5=106:kpds6=241:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:ordered sequence of data:anl:NAve=0
1932
15:254986:d=21113000:SWPER:kpds5=106:kpds6=241:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:ordered sequence of data:anl:NAve=0
1933
16:273854:d=21113000:WVDIR:kpds5=101:kpds6=1:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:sfc:anl:NAve=0
1934
17:288730:d=21113000:SWDIR:kpds5=104:kpds6=241:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:ordered sequence of data:anl:NAve=0
1935
18:312692:d=21113000:SWDIR:kpds5=104:kpds6=241:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:ordered sequence of data:anl:NAve=0
1936
19:339242:d=21113000:SWDIR:kpds5=104:kpds6=241:kpds7=0:TR=0:P1=0:P2=0:TimeU=1:ordered sequence of data:anl:NAve=0
1937

1938
=================================================================
1939
==5016==ERROR: LeakSanitizer: detected memory leaks
1940

1941
Direct leak of 40000 byte(s) in 1 object(s) allocated from:
1942
    #0 0x7fef05026bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
1943
    #1 0x55d833056e40 in main /home/runner/work/NCEPLIBS-grib_util/NCEPLIBS-grib_util/grib_utils/src/wgrib/wgrib.c:693
1944

```

**Comment by edwardhartnett** [comment]
I think this could be easily fixed, but with zero testing in place, I am reluctant to make changes in this code. Looking at the code, I see plenty to be concerned about...

**Comment by edwardhartnett** [comment]
We will not be working on the wgrib program.
